export const popularPokemonBatches = [
  ["Bulbasaur", "Ivysaur", "Charmander", "Charizard", "Squirtle"],
  ["Pikachu", "Raichu", "Meowth", "Geodude", "Gengar"],
  ["Eevee", "Snorlax", "Mewtwo", "Mew", "Dragonite"],
  ["Lucario", "Greninja", "Gardevoir", "Garchomp", "Arcanine"],
  ["Jigglypuff", "Psyduck", "Machamp", "Lapras", "Vaporeon"],
  ["Cyndaquil", "Totodile", "Chikorita", "Umbreon", "Espeon"],
  ["Blastoise", "Venusaur", "Butterfree", "Beedrill", "Pidgeot"],
  ["Rattata", "Fearow", "Arbok", "Sandslash", "Ninetales"],
  ["Wigglytuff", "Golbat", "Vileplume", "Parasect", "Dugtrio"],
  ["Persian", "Golduck", "Primeape", "Poliwrath", "Alakazam"],
  ["Victreebel", "Tentacruel", "Golem", "Rapidash", "Slowbro"],
  ["Magneton", "Dodrio", "Dewgong", "Muk", "Cloyster"],
  ["Hypno", "Kingler", "Electrode", "Marowak", "Hitmonlee"],
  ["Lickitung", "Weezing", "Rhydon", "Chansey", "Kangaskhan"],
  ["Seadra", "Starmie", "Scyther", "Jynx", "Electabuzz"],
  ["Mewtwo", "Mew", "Lugia", "Ho-Oh", "Celebi"],
];
//filter types 
export const pokemonTypeStyles = {
  normal: { background: "#A8A77A", text: "#111111" },
  fire: { background: "#EE8130", text: "#111111" },
  water: { background: "#6390F0", text: "#ffffff" },
  electric: { background: "#F7D02C", text: "#111111" },
  grass: { background: "#7AC74C", text: "#111111" },
  ice: { background: "#96D9D6", text: "#111111" },
  fighting: { background: "#C22E28", text: "#ffffff" },
  poison: { background: "#A33EA1", text: "#ffffff" },
  ground: { background: "#E2BF65", text: "#111111" },
  flying: { background: "#A98FF3", text: "#111111" },
  psychic: { background: "#F95587", text: "#111111" },
  bug: { background: "#A6B91A", text: "#111111" },
  rock: { background: "#B6A136", text: "#111111" },
  ghost: { background: "#735797", text: "#ffffff" },
  dragon: { background: "#6F35FC", text: "#ffffff" },
  dark: { background: "#705746", text: "#ffffff" },
  steel: { background: "#B7B7CE", text: "#111111" },
  fairy: { background: "#D685AD", text: "#111111" },
};

export const pokemonTypes = [
  "normal",
  "fire",
  "water",
  "electric",
  "grass",
  "ice",
  "fighting",
  "poison",
  "ground",
  "flying",
  "psychic",
  "bug",
  "rock",
  "ghost",
  "dragon",
  "dark",
  "steel",
  "fairy",
];

export const legendaryPokemon = [
  ["Kyogre", "Groudon", "Rayquaza", "Jirachi", "Deoxys"],
  ["Dialga", "Palkia", "Giratina", "Darkrai", "Arceus"],
  ["Reshiram", "Zekrom", "Kyurem", "Victini", "Keldeo"],
  ["Xerneas", "Yveltal", "Zygarde", "Diancie", "Hoopa"],
  ["Solgaleo", "Lunala", "Necrozma", "Zeraora", "Meltan"],
  ["Magmar", "Pinsir", "Tauros", "Gyarados", "Ditto"],
];
